### ISSUE TITLE
Don't install transformations?

### ISSUE THREAD

**Issue by user202729** [ceeac/boomerang#2]
Since `data/transformations` was deleted in https://github.com/ceeac/boomerang/commit/09e804f82c63819e540a24f1386287a79c441911, the corresponding install command should be deleted from `cmake-scripts/boomerang-install.cmake` too.

**Comment by ceeac** [comment]
Oh, you're right. Thanks!
If you want to open other issues, please do this at BoomerangDecompiler/boomerang, since that is the official repository now.
